package digital.container.storage.domain.model.file;

public enum FileStatus {
    IS_IN_ERROR,
    DO_NOT_SYNC,
    NOT_SYNC,
    SYNCHRONIZED,
    PROCESSED,
    FAILED_SYNC,
    FAILED_SYNC_IN_CONSUMER,
    FAILED_SYNC_IN_SEND_TO_MOM,
    FAILED_SYNC_IN_SEND_TO_AWSS3,
    FAILED_SYNC_IN_SEND_TO_CONTAINER,
    WAS_SENT_TO_CONTAINER,
    WAS_SENT_TO_MOM,
    NOT_FOUND_TAX_DOCUMENT_BY_CONSUMER,
    NOT_FOUND_TAX_DOCUMENT_BY_CONSUMER_BUT_WAS_SAVED_CONTINGENCY,
    FAILED_SYNC_BUT_WAS_SAVED_CONTINGENCY,
    FAILED_SYNC_IN_CONSUMER_BUT_WAS_SAVED_CONTINGENCY,
    FAILED_SYNC_IN_SEND_TO_MOM_BUT_WAS_SAVED_CONTINGENCY,
    FAILED_SYNC_IN_SEND_TO_AWSS3_BUT_WAS_SAVED_CONTINGENCY,
    FAILED_SYNC_IN_SEND_TO_CONTAINER_BUT_WAS_SAVED_CONTINGENCY;

}
