package digital.container.vo;

public enum ProcessTypeFile {
    ANYTHING,
    TAX_DOCUMENT,
    TAX_DOCUMENT_ANY,
    TAX_DOCUMENT_EVENT_CANCELLATION,
    TAX_DOCUMENT_EVENT_DISABLE,
    TAX_DOCUMENT_EVENT_LETTER_CORRECTION
}
